# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 ProtocolWarden
"""`cl reconcile index` — generated status dashboard (spec §3.4).

Reads every reconcilable repo's worksheet over local clones and emits
``console-reconciliation-status.md``: **public** repos itemized (counts, doc
gaps, prune-ready); **private** repos collapse into a single opaque aggregate
count with no identifying detail (AC11). Owner fields are genericized.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from context_lifecycle.io.yaml_io import load_yaml_safe
from context_lifecycle.reconcile.check import run_check
from context_lifecycle.reconcile.scrub import ScrubVocabulary, load_scrub_vocabulary
from context_lifecycle.reconcile.worksheet import WORKSHEET_RELPATH, load_worksheet


@dataclass
class RepoRow:
    repo: str
    done: int = 0
    partial: int = 0
    incomplete: int = 0
    doc_gaps: int = 0
    prune_ready: bool = False


@dataclass
class IndexResult:
    public_rows: list[RepoRow] = field(default_factory=list)
    private_count: int = 0
    warnings: list[str] = field(default_factory=list)


def load_public_repo_names(manifest_yaml: Path) -> set[str]:
    """Return the canonical names of public repos from a platform manifest YAML.

    A repo is public iff it appears with ``visibility: public``. Used to decide
    which repos may be itemized in the dashboard; everything else is opaque.
    """
    data = load_yaml_safe(manifest_yaml, default=None)
    names: set[str] = set()
    if not isinstance(data, dict):
        return names
    repos = data.get("repos")
    if not isinstance(repos, dict):
        return names
    for entry in repos.values():
        if not isinstance(entry, dict):
            continue
        if str(entry.get("visibility", "")).strip().lower() != "public":
            continue
        name = entry.get("canonical_name")
        if isinstance(name, str) and name.strip():
            names.add(name.strip())
    return names


def discover_worksheet_repos(clones_root: Path) -> list[Path]:
    """Return repo roots under ``clones_root`` that have a reconcile worksheet."""
    roots: list[Path] = []
    if not clones_root.is_dir():
        return roots
    for child in sorted(clones_root.iterdir()):
        if child.is_dir() and (child / WORKSHEET_RELPATH).is_file():
            roots.append(child)
    return roots


def build_index(
    clones_root: Path,
    public_names: set[str],
    *,
    vocab: ScrubVocabulary | None = None,
) -> IndexResult:
    """Aggregate worksheet status across all clones under ``clones_root``."""
    vocabulary = vocab if vocab is not None else load_scrub_vocabulary()
    result = IndexResult()
    for repo_root in discover_worksheet_repos(clones_root):
        ws = load_worksheet(repo_root)
        is_public = ws.repo in public_names
        if not is_public:
            result.private_count += 1
            continue
        row = RepoRow(repo=ws.repo)
        for it in ws.items:
            if it.is_cross_repo(ws.repo):
                continue
            if it.status == "done":
                row.done += 1
            elif it.status == "partial":
                row.partial += 1
            elif it.status == "incomplete":
                row.incomplete += 1
        chk = run_check(repo_root, vocab=vocabulary, worksheet=ws)
        row.doc_gaps = len(chk.doc_gaps)
        row.prune_ready = chk.green
        result.public_rows.append(row)
        result.warnings.extend(f"{ws.repo}: {w}" for w in ws.warnings)
    return result


def render_index(result: IndexResult) -> str:
    """Render the dashboard markdown. Private repos appear only as a count."""
    lines = [
        "# `.console/` Reconciliation — status",
        "",
        "_Generated by `cl reconcile index`. Do not hand-edit._",
        "",
        "## Public repos",
        "",
        "| repo | done | partial | incomplete | doc-gaps | prune-ready |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in sorted(result.public_rows, key=lambda r: r.repo):
        ready = "yes" if row.prune_ready else "no"
        lines.append(
            f"| {row.repo} | {row.done} | {row.partial} | {row.incomplete} "
            f"| {row.doc_gaps} | {ready} |"
        )
    if not result.public_rows:
        lines.append("| _(none)_ | | | | | |")
    lines += [
        "",
        "## Private repos",
        "",
        f"{result.private_count} private repo(s) tracked (aggregate; not itemized).",
        "",
    ]
    return "\n".join(lines)
